### ISSUE TITLE
Rethink all project assignments

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/rin3-fall-2024#2]

**Comment by graciellehigino** [comment]
# Welcome to R in 3 Months

- [x]  Add a lesson about Discord
- [x]  Add a lesson about project organization to use in the program (folder for your own notes, folders for assignments, etc) - 📹 https://muse.ai/e/Lghzsc2
- [x]  Highlight that the Your Turn sections are supposed to create temporary projects. Students should archive or delete the files created in each lesson.

# **Week 2: Data Wrangling and Analysis**


**Before you do anything else, please check in with your coach and confirm that the data you are using is a good fit for the first few weeks of R in 3 Months. If you need some generic data, [we have created a repository with several simple datasets for you to work with](https://github.com/rfortherestofus/rin3-datasets). Once you've done that, please do the following:**

For this week, we want you to do some wrangling and analysis of your data. To do this assignment, you'll do the following:

1. Create a new project in a new directory called “FirstName_LastName”. Then create subfolders following our recommendation in this lesson .
```
    FirstName_LastName
      code/
      data-raw/
      data/
      FirstName_LastName.Rproj
```
3. Store your data in the `data-raw` folder.
4. Create an R script file, save it to the `code` folder, and add three sections (use ctrl + shift + R to open the section box):
    1. Load packages
    2. Import data
    3. Questions about the data
5. Under the “load packages” section you will load your packages
6. Under the “Import data” section, write the correct code to import your data as a CSV (if your data is in another format, let us know and we can help you convert it). Notice you will need to specify the file path starting with `“data-raw”`.
7. Take some time to explore your dataset as we did [in this lesson](https://rfortherestofus.com/courses/r-in-3-months-fall-2024/lessons/examine-our-data-v2). No need to save your code in your script at this stage, but if you want to, add a comment or a new section for it. We recommend using pen and paper to take notes.
8. Under the “Questions about the data” section, add, as comments, **three** questions that you want to answer with your data. 
9. Under each question, create the correct code to answer it.
10. Once you've completed your work, compress your `FirstName_LastName` project folder and upload it to the form below.
11. If you have any specific questions, add those in the form below as well.

- [x]  Update the Week 2 Project Assignment page with the new instructions and new video
📹 Instructions: https://muse.ai/v/MHtS6pa
📹 Example: https://muse.ai/e/LUkVxiK

# **Week 3: Data Visualization**

For this week, we want you to make some data viz with your data. We're not looking for something beautiful or perfect! We want to see you understand how to use `ggplot2` and which parts of your dataset you're interested in visualizing. Here's an example of what we're looking for: [https://github.com/graciellehigino/rin3-project-templates/tree/main/rin3-week3-example](https://github.com/graciellehigino/rin3-project-templates/tree/main/rin3-week3-example)

Here are the steps for this week's assignment:

1. Open your project from the Week 2 assignment.
2. Again, take some time to come up with **three** questions about your dataset. They don't need to be different from the questions you created last week, but they need to be possible to answer using data visualization.
3. Create a new section called “Data visualization” and add your three questions there, as comments.
4. Under each question, write the right code to produce the visualization intended.
5. Once you've completed your work, compress your `FirstName_LastName` project folder and upload it to the form below.
6. If you have any specific questions, add those in the form below as well.


- [x]  Update the Week 3 Project Assignment page with the new instructions and new video
📹 Instructions: https://muse.ai/v/5it2G5p
📹 Example: https://muse.ai/e/qpW9Efd

# **Week 4: Quarto**

For this week, we want you to create a Quarto document. To do this, you'll take code from [last week's data viz project assignment](https://rfortherestofus.com/courses/r-in-3-months-fall-2023/lessons/fall-2023-week-3-project-assignment) and turn it into a Quarto document. Here's an example of what we're looking for: [https://github.com/graciellehigino/rin3-project-templates/tree/main/rin3-week4-example](https://github.com/graciellehigino/rin3-project-templates/tree/main/rin3-week4-example)

Here are the steps for this week's assignment:

1. Open your project from the Week 3 assignment.
2. Create a Quarto document and save it to the root folder (**not** in your `code` folder).
3. Paste your code from your R script into your new Quarto document.
4. Break your code into code chunks as appropriate, making sure to remove or comment out any code that does not generate new objects or plots.
5. Adjust your code chunk options so that you only see results, not warnings, messages, code, etc.
6. Add text using markdown as you learned in the Text lesson. Use headings, bold, italics, and lists as appropriate. Use this opportunity to add context to your report, and explain to the reader what they should be paying attention to.
7. Make sure you can render your document. Notice this will create new files and folders in your root folder, and it will look a bit messy. We will learn how to deal with it in the Advanced Quarto lessons. For now, you can delete the *.html file and the <your_project>_files folder before submitting your assignment for review. **Make sure to keep your *.qmd file.**
8. Once you've completed your work, compress your `FirstName_LastName` project folder and upload it to the form below.
9. If you have any specific questions, add those in the form below as well.

- [x]  Update the Week 4 Project Assignment page with the new instructions and new video
📹 Old: https://muse.ai/v/JP6fP1T
📹 New: https://muse.ai/e/oYKQ135

# **Week 8: Advanced Data Wrangling (Part 2)**

For this week's project assignment, we want you to tidy your data using 
the various functions you have learned in the last two weeks. You should do this in an R script file, saving your clean and tidy data as an RDS file. Essentially, we want you to do the same thing that David shows in 
the [Bring It All Together (Advanced Data Wrangling) lesson](https://rfortherestofus.com/courses/r-in-3-months-fall-2023/lessons/bring-it-all-together-advanced-data-wrangling), but for your data.

Here are the steps for this week's assignment:

1. Open your project from the Week 4 assignment.
2. Open your R script and edit it to include a section called "Advanced Data Wrangling"
⚠️ If you are starting with a new dataset, feel free to create a new R script!
3. Add the three comments below on your script:
```
# Check for tidy principles (each columns is a variable, each cell is a single value, every row is an observation)
# Identify repetitive tasks and create a function
# Export clean data into the data folder
```
5. Add code below each of these three comments to complete each of these tasks. Make sure you can export your cleaned data into your `data` folder.
6. Once you've completed your work, compress your `FirstName_LastName` project folder and upload it to the form below.
7. If you have any specific questions, add those in the form below as well.

- [x]  Update the Week 8 Project Assignment page with the new instructions and new video
📹 Instructions: https://muse.ai/v/3ShH4Tg 
📹 Example: https://muse.ai/e/H1XifVs

# **Week 11: Advanced Data Visualization (Part 2)**

Your assignment for this week is to improve a previous visualization and/or create a new visualization. Use the principles you learned about in the Advanced Data Visualization lessons to guide your work!

Here are the steps for this week's assignment:

1. Open your project from the Week 8 assignment.
2. Rewrite your Quarto document in a way that you'll only import your cleaned data and plot them. You should create the necessary code chunks to load packages and read in your RDS files from your `data` folder.
5. Create 1-3 plots using at least one task from each group of tasks below:
    1. Pipe data into ggplot; reorder plots to highlight findings; or use color to highlight findings
    2. Add descriptive labels to your plots; customize your fonts; or use annotations to explain 
    4. Create a custom theme; use titles to highlight findings; or try new plot types
6. Break your code into code chunks as appropriate, making sure to remove or comment out any code that does not generate new objects or plots.
7. Adjust your code chunk options so that you only see results, not warnings, messages, code, etc.
8. Add text using markdown as you learned in the Text lesson. Use headings, bold, italics, and lists as appropriate. Use this opportunity to add context to your report, and explain to the reader what they should be paying attention to.
9. Make sure you can render your document. Notice this will create new files and folders in your root folder, and it will look a bit messy. We will learn how to deal with it in the Advanced Quarto lessons. For now, you can delete the *.html file and the <your_project>_files folder before submitting your assignment for review. **Make sure to keep your *.qmd file.**.  
10. Once you've completed your work, compress your `FirstName_LastName` project folder and upload it to the form below.
11. If you have any specific questions, add those in the form below as well.

- [ ]  Update the Week 11 Project Assignment page with the new instructions and new video
📹 https://muse.ai/e/k6mdKEN

**Comment by graciellehigino** [comment]
# **Week 13: Final Project**

Criteria/check boxes for the final project:

- [ ]  Your project is organized in a way that it has a clear separation between code files, data (raw and clean), outputs and documentation;
- [ ]  Your code is well commented;
- [ ]  You have a consistent naming convention for your files and objects;
- [ ]  Your object names are descriptive;
- [ ]  Your code is fully reproducible;
- [ ]  Your final report contains at least a data wrangling and a data visualization section; the code to produce them is not necessarily in the quarto document (they can be called in using the source function).

📹 https://muse.ai/e/soq4U92

**Comment by graciellehigino** [comment]
I've added links to the recorded lessons from weeks 1 - 8 for review in their respective sections above. I decided to wait to record the last two until we have agreed on the schedule of lessons, otherwise, I will record the videos without mentioning the week number 😅


All videos are in our Fall 2024 collection on Muse: https://muse.ai/collections/3e8Esfx

**Comment by dgkeyes** [comment]
These videos are looking good! A few comments:

It would be nice to have you actually create a fake project and show real examples of project assignments each week. So, for example, in the data viz assignment in week 3, you could show how you would create a question and then create a data viz to answer the question. Could you do that and edit those videos into what you already created?

In the week 4 video, you use RMarkdown-style code chunk options:

![CleanShot 2024-07-22 at 20 41 14@2x](https://github.com/user-attachments/assets/7a5e51e2-74d0-410b-b701-8d0d9834ef4b)

I'm worried this will confuse people. Could you please remove this and just use Quarto-style hash pipe code chunk options?

For the week 8 assignment, I know I told you the assignment was ok, but now that I think about it, I think we need to emphasize tidy data more in the assignment. What I'm thinking is we make the assignment to first tidy your data and from there then people answer the 3 questions that you talk about in the current version of the video. How does that sound?

**Comment by graciellehigino** [comment]
Hi David! The new videos are up. I decided to make the assignment examples as they were extra videos, or the assignment videos would be super long. I worried they would differ too much from the other videos in the program. So the lesson page should contain the instruction video as the main one and an extra video in a section below. Let me know what you think!

About week 4, I'm not sure what to do, but I'm pretty confident that we can replace the old video and use only the example.

Also, I have redesigned the week 8 assignment and now students won’t need to come up with three questions, I just asked them to check for tidy principles, identify repetitive tasks and create a function for them, and export the cleaned data. I think it’s enough! =D
So for this lesson, I will only have one video - the new one with an example script on the video.

I have also added the week 11 assignment explanation. This one has fewer details as it's the last one before the final assignment, so I figured I didn't need to explain too much.

Let me know what you think!

**Comment by dgkeyes** [comment]
Thanks! I'll review these soon (hopefully tomorrow) and get back to you.

**Comment by dgkeyes** [comment]
@graciellehigino just had a chance to review everything. All looks good.

On week 4, I think we can just use the new video.

Do you want to go ahead and add these videos and instructions to the website? No rush on this (I know you're on vacation next week).

**Comment by dgkeyes** [comment]
Just one thing: since we're removing the GitHub materials I'm going to spread the advanced data wrangling stuff over three weeks. That means that what you have listed as week 8 will actually be week 9.

**Comment by dgkeyes** [comment]
No wait, that's not right. It is week 8. My apologies (counting weeks is one thing I can never quite master).

Two other things: 

1. I removed all of the current project assignment lessons. Rather than have you edit those (which would mess things up for previous cohorts), please just make new lessons. I'll add the assignment submission forms once Jack has implemented those.
2. Can you also record a very short video explaining the final assignment?
